function SOL_400_IMPF_LBA_FUNC_MAIN(SCALE_FACTOR,PRE_RUN_FILE_NAME,IMPF_FILE_NAME_LBA)
%% CREATE NEW .DAT FILE
FID_400 = fopen(IMPF_FILE_NAME_LBA,'w'); %% NEW DAT FILE

%% IMPORT PRE-RUN
% PRE_RUN_FILE_NAME = 'cyliinder_ref_dlr_sol_105_safe.op2';
% PRE_RUN_FILE_NAME = 'cyliinder_ref_dlr_sol_105_TEST.op2';
UNIT = 31;
% assign_preRun_sol(FID_400,PRE_RUN_FILE_NAME,UNIT)
assign_preRun_sol_ICEBOX(FID_400,PRE_RUN_FILE_NAME,UNIT)

%% EXCUTITIVE CONTROL
sol_type = 400;
excutitive_control(FID_400,sol_type)
%% ECHO BULK DATA

fprintf(FID_400,'ECHO = NONE\n');

%% ASSIGN IMPERFECTION CASE
IMPERFECT_ID = 17;
assign_imperfection(FID_400,IMPERFECT_ID)

%% SET
SET_ID = 4;
SET_func(FID_400,SET_ID)
% SET_ID = [];
%% CASE CONTROL
SORT_TYPE = 'SORT1'; % SORT1 or SORT2

% ANALYSIS_TYPE1 = 'NLSTATIC';
ANALYSIS_TYPE1 = 'STATICS';

SubCaseID1 = 1;
StepID1 = 1;

ANALYSIS_TYPE2 = 'buckl';
% ANALYSIS_TYPE2 = 'BUCK';
SubCaseID2 = 2;
EIGmethodID = 15;

case_control_IMPF_LBA(FID_400,SubCaseID1,SubCaseID2,StepID1,ANALYSIS_TYPE1,ANALYSIS_TYPE2,SET_ID,EIGmethodID,SORT_TYPE);

%% SET1 OR SET3
SETi_ID = 14;
% SETi_ID = ALL;
SET3_func(FID_400,SETi_ID)

%% BULK SECTION BEGINING
begin_bulk(FID_400)


%% define_impCase

MODE_TYPE = 1;
nIMP_CASE = 1:length(SCALE_FACTOR);
% define_impCase(FID_400,SubCaseID2,StepID1,IMPERFECT_ID,SETi_ID,MODE_TYPE,nIMP_CASE,SCALING_FACTOR,UNIT)
define_impCase_static(FID_400,SubCaseID2,IMPERFECT_ID,SETi_ID,MODE_TYPE,nIMP_CASE,SCALE_FACTOR,UNIT);
%% REQUEST EIGENVALUE OUTPUTS
NROOT = 10;
MIN =0.0001;
MAX = 1000;
METHOD = 'LAN';
RANGE = 'y'; 

eigval_request_EIGRL(FID_400,NROOT,EIGmethodID,MIN,MAX,METHOD,RANGE);
% % eigval_request_EIGR(FID_400,NROOT,EIGmethodID,MIN,MAX,METHOD,RANGE)
% % eigval_request_EIGB(FID_400,NROOT,EIGmethodID,MIN,MAX,METHOD,RANGE)

%% REQUEST OUTPUT FILES
outputFile_request_400(FID_400)
%%
fclose(FID_400);

end








